### PR TITLE
Remove the need to override neterror

### PR DESCRIPTION
**Pull request by mkaply**
Try this out and see what you think.

sorry I screwed up your tabs.

Who uses tabs?

### CODE REVIEW

**Comment by mkaply** [comment]
Kai:

Any reason you haven't taken this one?

I'd like to get the Webconverger on AMO upgraded and it needs this.

**Comment by kaihendry** [comment]
No reason other than I haven't got around to testing it!

**Comment by mkaply** [comment]
It worked quite well in my testing and we'll never have to mess with netError again.

FYI, the reason I'm asking is because someone said the Webconverger on AMO isn't working for them.

**Comment by kaihendry** [comment]
Please feel free to merge and upload to AMO.

**Comment by mkaply** [comment]
I want you to at least test once :).

Or do you trust me?

**Comment by kaihendry** [comment]
I will test when I merge with Webconverger OS, I trust you with AMO! 😄

**Pull request merged**
