### PR TITLE
Add a preference to force safe search

### PR DESCRIPTION
**Pull request by mkaply**

### CODE REVIEW

**Comment by mkaply** [comment]
Obviously you'd change this to google.co.uk for this customer. I don't see of a way to do it generically except with regex.

Or maybe just check for http://www.google. and alway add the safe stuff?

**Comment by mkaply** [comment]
Here's some info on how to do it for yahoo and bing as well.

http://www.safesquid.com/content-filtering/how-enforce-google-yahoo-and-bing-safe-search

I think I can make this better.

**Comment by mkaply** [comment]
I'm not a regex guru, so I can't figure out all of it. 

It's something like this:

      if (/.*\.google\..*/.test(httpChannel.URI.host)) {
        if (/^(custom|search|images)\?/.test(httpChannel.URI.path)) {
          if (httpChannel.URI.spec.indexOf("safe=strict") == -1) {
            httpChannel.redirectTo(Services.io.newURI(httpChannel.URI.spec + "&safe=strict", null, null));
          }
        }
        return;
      }

but I can't figure out how to do the custom/search/images check.

**Comment by mkaply** [comment]
OK, this is done. It works really really well. I've enabled it for bing, yahoo and google.

**Comment by kaihendry** [comment]
Noticed this seems to exclude the earlier extensions.webconverger.proxyusername & extensions.webconverger.proxypassword modifications. Wonder how github managed to merge it so easily. :/

**Comment by kaihendry** [comment]
https://github.com/Webconverger/webc/blob/master/etc/webc/extensions/webconverger/modules/webconvergerModule.jsm

**Comment by kaihendry** [comment]
We should also support DDG, since that's the default search engine :) https://duck.co/help/features/safe-search

**Comment by kaihendry** [comment]
Hmm, in my testing, it doesn't appear to work. Am I missing something @mkaply ?

http://s.natalian.org/2015-01-26/1422257456_1362x740.png
 http://s.natalian.org/2015-01-26/webconverger.xpi

**Comment by mkaply** [comment]
You can't use an alert to test this.

Are you saying when you go to google and search on "porn" it still shows results?

As far as the proxy code goes, it wasn't in my repo. No idea how that happened...

**Comment by mkaply** [comment]
And yes, I'll add DDG.

**Comment by kaihendry** [comment]
Yes, I tested it and porn still showed with "boobs". ;) Did you try my XPI yourself? How else can I test it? Come to think of it, perhaps the module was missing from the manifest.

**Comment by mkaply** [comment]
> Yes, I tested it and porn still showed with "boobs". ;) Did you try my XPI yourself? How else can I test it, if not alert?

Didn't get a chance. I will.

You could do 

Services.prompt.alert(null, "", "foo");

or put something on the console

Components.utils.reportError("foo");

**Comment by mkaply** [comment]
Yeah, we're not loading the webconvergerService.js which is how the module gets loaded.

**Comment by mkaply** [comment]
I did a new pull for branch loadservice to load the moduke.

I've put another commit on this branch to add DDG.

**Comment by mkaply** [comment]
OK, I know what I keep screwing up. I'm using my own repository and branching instead of yours. So I'm forgetting to merge with origin. Argh. I'll fix.

**Pull request merged**
